version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./../nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
    links:
      - app:app
  app:
    build:
      context: ./
      dockerfile: Dockerfile.app
    image: template-app
    volumes:
      - ./../../:/usr/src/app
    ports:
      - '3000:3000'